# Generated by Django 5.2 on 2025-09-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО тренера')),
                ('type_sport', models.CharField(max_length=255, verbose_name='Вид спорта')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to='coaches/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='День недели')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'День недели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид спорта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид спорта',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fanat.coach_new')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fanat.weekday')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fanat.workouttype')),
            ],
        ),
    ]
