# Generated by Django 5.2 on 2025-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
