# Generated by Django 5.2 on 2025-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probnic',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
