# Generated by Django 5.2 on 2025-05-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0002_probnic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probnic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
