# Generated by Django 5.2 on 2025-09-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0002_schedule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='slug',
        ),
    ]
