# Generated by Django 5.2 on 2025-05-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0003_alter_probnic_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
