# Generated by Django 5.2 on 2025-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0003_remove_schedule_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttype',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
