# Generated by Django 5.2 on 2025-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0004_delete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_sport', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to='coaches/')),
            ],
        ),
    ]
