# Generated by Django 5.2 on 2025-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0005_coach_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probnic',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='coach_new',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='probnic',
            index=models.Index(fields=['time_create'], name='fanat_probn_time_cr_35bf38_idx'),
        ),
    ]
