# Generated by Django 5.2 on 2025-08-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanat', '0006_alter_probnic_options_coach_new_is_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Probnic',
        ),
    ]
